### ROOT
GET http://localhost:5000/

### USER
POST http://localhost:5000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "username":"anthonyfinix",
    "password":"anthonyfinix@123"
}

### REGISTER
POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "Anthony Finix",
    "username": "anthonyfinix",
    "password": "anthonyfinix@123",
    "confirmPassword": "anthonyfinix@123",
    "email": "anthonyfinix@gmail.com"
}

### 404
GET http://localhost:5000/notFound